# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tI3Sz3Hkh_F8o4L1i4ZhNqYKVm-s7VZN
"""

import streamlit as st
import torch
import torch.nn as nn
from torchvision import transforms
from PIL import Image
import timm
import numpy as np
import os
import random

# --- 1. Konfigurasi Dasar dan Definisi Kelas ---

# Nama file bobot model ViT yang sudah dilatih
MODEL_WEIGHTS_PATH = 'ViT_model.pth'
CLASSES_FILE_PATH = 'classes.txt'
IMG_SIZE = 224
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Fungsi untuk memuat daftar kelas secara dinamis
def load_classes(CLASSES_FILE_PATH):
    """Memuat daftar kelas dari file teks."""
    try:
        with open(CLASSES_FILE_PATH, 'r') as f:
            # Setiap baris adalah satu nama kelas
            classes = [line.strip() for line in f if line.strip()]
        return classes
    except FileNotFoundError:
        st.error(f"Gagal memuat kelas: File '{file_path}' tidak ditemukan.")
        st.info("Silakan buat file classes.txt yang berisi satu nama kelas per baris.")
        # Mengembalikan daftar dummy jika file tidak ditemukan
        return ["Unknown 0", "Unknown 1"]

# Muat kelas di awal
CLASSES = load_classes(CLASSES_FILE_PATH)
NUM_CLASSES = len(CLASSES)

# --- 2. Definisi Transformasi Data ---
# Harus sama persis dengan val_transform yang digunakan saat pelatihan!
data_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]),
])

# --- 3. Fungsi Memuat Model ---
@st.cache_resource
def load_model():
    """Memuat model ViT-Tiny dari timm dan memuat bobot yang telah dilatih."""
    try:
        # Inisialisasi model ViT-Tiny
        model_name = 'vit_tiny_patch16_224'
        model = timm.create_model(model_name, pretrained=False, num_classes=NUM_CLASSES)

        # Cek apakah file bobot ada
        if os.path.exists(MODEL_WEIGHTS_PATH):
            model.load_state_dict(torch.load(MODEL_WEIGHTS_PATH, map_location=DEVICE))
            loaded = true
        else:
            # Gunakan bobot pretrained ImageNet sebagai fallback jika bobot latihan tidak ditemukan
            model = timm.create_model(model_name, pretrained=True, num_classes=NUM_CLASSES)
            loaded = false

        model.to(DEVICE)
        model.eval()
        return model
    except Exception as e:
        st.error(f"Gagal memuat model. Error: {e}")
        return None

# --- 4. Fungsi Prediksi ---
def predict_image(model, image):
    """Memproses gambar, menjalankan inferensi, dan mendapatkan prediksi."""
    try:
        # 1. Terapkan transformasi
        tensor_image = data_transform(image).unsqueeze(0).to(DEVICE)

        # 2. Inferensi
        with torch.no_grad():
            outputs = model(tensor_image)

        # 3. Hitung probabilitas dan kelas
        probabilities = nn.functional.softmax(outputs, dim=1)
        confidence, predicted_index = torch.max(probabilities, 1)

        # 4. Ambil nama kelas dan confidence score
        predicted_class_name = CLASSES[predicted_index.item()]
        confidence_score = confidence.item()

        return predicted_class_name, confidence_score
    except Exception as e:
        st.error(f"Terjadi error saat menjalankan prediksi: {e}")
        return None, 0.0

# --- 5. SETUP APLIKASI STREAMLIT ---
def main():

    model, loaded = load_model()

    if loaded:
        st.toast("✅ Bobot model berhasil dimuat.", icon='🎉')
    else:
        st.warning(f"⚠️ Bobot '{MODEL_WEIGHTS_PATH}' tidak ditemukan. Menggunakan pretrained ImageNet.")

    st.set_page_config(
        page_title="ViT Face Recognition Demo",
        layout="wide",
        initial_sidebar_state="auto"
    )

    st.title("👨‍🔬 ViT-Tiny Face Recognition Demo")
    st.markdown("Aplikasi demonstrasi pengenalan identitas wajah menggunakan **Vision Transformer (ViT-Tiny)** yang telah di-*fine-tune* untuk **{NUM_CLASSES} kelas** (orang).")

    # Muat model
    model = load_model()

    if model is None:
        st.stop() # Berhenti jika model gagal dimuat

    # Input Gambar
    uploaded_file = st.file_uploader(
        "Unggah Gambar Wajah (JPG/JPEG/PNG)",
        type=["jpg", "jpeg", "png"]
    )

    # Kolom untuk tampilan
    col1, col2 = st.columns(2)

    with col1:
        if uploaded_file is not None:
            # Tampilkan gambar yang diunggah
            image = Image.open(uploaded_file).convert('RGB')
            st.image(image, caption='Gambar Wajah yang Diunggah', use_column_width=True)

            # Tombol prediksi
            if st.button("Tampilkan Prediksi Identitas", type="primary"):
                with st.spinner('Memproses inferensi model ViT...'):
                    # Lakukan Prediksi
                    predicted_name, confidence_score = predict_image(model, image)

                # Simpan hasil di state untuk ditampilkan di col2
                st.session_state['prediction_result'] = {
                    'name': predicted_name,
                    'confidence': confidence_score
                }
        else:
            st.info("Silakan unggah gambar wajah untuk memulai.")

    with col2:
        st.header("Hasil Analisis")

        # Menampilkan hasil jika ada di session state
        if 'prediction_result' in st.session_state and st.session_state['prediction_result']['name'] is not None:
            result = st.session_state['prediction_result']

            # Tampilkan kartu hasil
            confidence_percentage = result['confidence'] * 100

            if confidence_percentage >= 90:
                alert_type = "success"
                status_icon = "✅"
            elif confidence_percentage >= 70:
                alert_type = "warning"
                status_icon = "🟡"
            else:
                alert_type = "error"
                status_icon = "❌"

            st.subheader(f"{status_icon} Identitas Diprediksi:")
            st.markdown(f"""
                <div style="background-color: #eef4ff; padding: 20px; border-radius: 10px; border-left: 5px solid #4f46e5;">
                    <h3 style="margin: 0; color: #1e40af;">{result['name']}</h3>
                </div>
            """, unsafe_allow_html=True)

            st.metric(
                label="Tingkat Keyakinan (Confidence)",
                value=f"{confidence_percentage:.2f}%",
                delta_color=alert_type
            )

            st.markdown(f"Model ViT (Vision Transformer) memprediksi bahwa wajah ini milik **{result['name']}** dari **{NUM_CLASSES}** identitas yang dilatih.")
        else:
            st.info("Hasil prediksi akan muncul di sini setelah Anda mengunggah gambar dan menekan tombol prediksi.")

if __name__ == '__main__':
    main()
